### ISSUE TITLE
Update Exporter to use Sinopia API/MongoDB

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_exporter#146]
The current Trellis export does not use the new Sinopia API with MongoDB. We need to update the Exporter to use the Sinopia API to extract the resources and resource templates, now in RDF, and generate a zip file of the contents per group. 

Requires a new Resources list endpoint  https://github.com/LD4P/sinopia_api/pull/22.

**Comment by justinlittman** [comment]
@jermnelson Do we want to re-implement as close to existing as possible or with changes?

**Comment by jermnelson** [comment]
> @jermnelson Do we want to re-implement as close to existing as possible or with changes?
Good question; Asking on the Slack if there are any changes people would like to see in the exports and I'll update this ticket.

**Comment by jyssy** [comment]
I will need to re-examine the export in light of your dB changes. I know I am in the BF2MARC conversion affinity group and want to track this. for instance, I think LC's conversion is using RDFXML - so i am not sure yet how to use my exported JSON-LD in a conversion workflow. Comments will come - but I wanted to drop these comments here. thanks

**Comment by timathom** [comment]
@jermnelson, In Yale's work with metaphactory, we needed to implement a postprocessing workflow to "skolemize" the blank nodes in the Sinopia export so that each RDF resource would have its own URI. I think it might be generally useful if Sinopia could do this by default in the JSON-LD output, since blank nodes are typically more of a pain to work with.
